import { chromium } from 'playwright';
const base = 'https://njsoft-stream.njcreative123.workers.dev';
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const errors = [];
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
page.on('pageerror', e => errors.push('PAGE_ERR: ' + e.message));
await page.goto(base + '/#ai', { waitUntil: 'domcontentloaded', timeout: 25000 });
await page.waitForTimeout(2500);
await page.locator('.chat-input').scrollIntoViewIfNeeded();
await page.fill('#chatIn', 'Hello NJ! Kaisa hai?');
await page.keyboard.press('Enter');
await page.waitForTimeout(12000);
const msgs = await page.locator('#chatMsgs .msg').count();
const userMsg = await page.locator('#chatMsgs .msg.user p').last().textContent().catch(() => '');
const lastAi = await page.locator('#chatMsgs .msg.ai p').last().textContent().catch(() => '');
console.log('AI msgs total:', msgs);
console.log('user msg:', (userMsg||'').trim().slice(0,60));
console.log('last ai reply:', (lastAi||'').slice(0,120).replace(/\n/g,' '));
console.log('errors:', JSON.stringify(errors.filter(e => !/favicon|401|403/i.test(e))));
await page.screenshot({ path: 'FINAL_mobile_ai_reply.png' });
await browser.close();
