import { chromium } from 'playwright';
const BASE='https://njsoft-stream.njcreative123.workers.dev/';
const CHROME='/data/user/0/gptos.intelligence.assistant/files/rootfs/root/.cache/ms-playwright/chromium-1243/chrome-linux-arm64/chrome';
const b=await chromium.launch({executablePath:CHROME,args:['--no-sandbox']});
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const p=await ctx.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message.slice(0,120)));
p.on('console',m=>{ if(m.type()==='error') errs.push('C:'+m.text().slice(0,120)); });
await p.goto(BASE+'#tv',{waitUntil:'domcontentloaded',timeout:60000}).catch(e=>errs.push('NAV:'+e.message.slice(0,80)));
await p.waitForTimeout(9000);
const healthLine=await p.locator('#tvHealthMsg').textContent().catch(()=>'(none)');
const hindiBtn=await p.locator('[data-hindi-first]').count();
const workingBtn=await p.locator('[data-vwork]').count();
console.log('HEALTH LINE:', JSON.stringify(healthLine));
console.log('hindi-first btn:',hindiBtn,'| working btn:',workingBtn,'| cards:',await p.locator('.tv-card').count());
await p.screenshot({path:'/root/johnny.heliohost./final3_tv_health.png'});
// Hindi first -> clicks first Hindi card -> check player
await p.locator('[data-hindi-first]').click();
await p.waitForTimeout(1500);
const hCards=await p.locator('.tv-card').count();
const hNames=await p.locator('.tv-card .tc-name, .tv-card h4, .tv-card h3').allTextContents().catch(()=>[]);
const firstCard=p.locator('.tv-card').first();
const firstTitle=(await firstCard.textContent().catch(()=>'')).slice(0,60);
await firstCard.click();
await p.waitForTimeout(8000);
const vids=await p.locator('video').count();
const playing=await p.evaluate(()=>{ const v=document.querySelector('video'); return v?{ready:v.readyState,cur:v.currentTime||0,src:(v.currentSrc||'').slice(0,90),wait:!(v.paused),error:v.error?String(v.error.code):null}:null; }).catch(()=>null);
console.log('HINDI CARDS:',hCards,'| first:',JSON.stringify(firstTitle));
console.log('VIDEO:',JSON.stringify(playing, null, 1));
await p.screenshot({path:'/root/johnny.heliohost./final3_hindi_play.png'});
console.log('ERRORS:', JSON.stringify([...new Set(errs)].slice(0,8)));
await b.close();
