name = "njsoft-stream"
main = "src/workers/index.js"
compatibility_date = "2024-09-01"

[vars]
ENVIRONMENT = "production"
WELCOME_MESSAGE = "NJStream v5.0 — Live TV, Movies, Books, Telegram, AI"
TG_CHAT_ID = "-1002514429549"

WORKER_URL = "https://njsoft-stream.njcreative123.workers.dev"
[[d1_databases]]
binding = "CATALOG_DB"
database_name = "njsoft-catalog"
database_id = "a8cf8fd3-fa70-42ed-b83c-83dc326909a9"

[[kv_namespaces]]
binding = "KV_STORE"
id = "e1889fcdeca94f2abe934162ade34db8"

[triggers]
crons = ["0 */6 * * *"]
